name: dynamic_carousel_indicator
description: The Dynamic Carousel Indicator provides an interactive indicator for dynamic carousels.
version: 1.0.0
repository: https://github.com/chanapongpan/dynamic_carousel_indicator

environment:
  sdk: ^3.1.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
